version: "3.9"

services:
  # =====================
  # 🧠 BACKEND SERVICE
  # =====================
  blog_api:
    build:
      context: ./blog_service
      dockerfile: Dockerfile
    container_name: blog_service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/blog_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    networks:
      - backend

  # =====================
  # 🗄️ MYSQL DATABASE
  # =====================
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  # =====================
  # ⚡ REDIS CACHE
  # =====================
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

# =====================
# 🌐 NETWORKS & VOLUMES
# =====================
networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
