services:
  redis:
    image: redis:7
    container_name: blog-redis
    ports:
      - "6379:6379"
    networks:
      - blog-network

  blog-api:
    build:
      context: ..
    container_name: blog-api
    depends_on:
      - redis
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    networks:
      - blog-network
    entrypoint: ["./wait-for-it.sh", "redis", "6379", "--", "java", "-jar", "blog-api.jar"]

networks:
  blog-network: